### ISSUE TITLE
Question about graph convolutional layer in LR-GCCF

### ISSUE THREAD

**Issue by hegongshan** [newlei/LR-GCCF#3]
According the original paper, W^k is the linear transformation.

![image](https://user-images.githubusercontent.com/33055241/109268474-1a58c080-7846-11eb-9bc2-7a751d3dbb89.png)

However, W^k seems to be absent in the code.
https://github.com/newlei/LR-GCCF/blob/17c160affc2facb5c34f9243691bb725efdbe56e/code/train_amazons.py#L141

**Comment by newlei** [comment]
Thank you for your question. In parameter settings of the original paper, we set that Y equals the identity matrix, while Y^K= =W^0 W^1...W^K. Thus, we actually set W as the identity matrix, naturally, the W is not explicitly written in code.

**Comment by hegongshan** [comment]
> Thank you for your question. In parameter settings of the original paper, we set that Y equals the identity matrix, while Y^K= =W^0 W^1...W^K. Thus, we actually set W as the identity matrix, naturally, the W is not explicitly written in code.

OK! Thank you for your answer!

**Comment by Lim-Sung-Jun** [comment]
> > Thank you for your question. In parameter settings of the original paper, we set that Y equals the identity matrix, while Y^K= =W^0 W^1...W^K. Thus, we actually set W as the identity matrix, naturally, the W is not explicitly written in code.
> 
> OK! Thank you for your answer!

could you explain it more detail? where is identity matrix? in the (A+I)?
