### ISSUE TITLE
About coding cannot directly run

### ISSUE THREAD

**Issue by Littleyezi** [newlei/LR-GCCF#5]
Hi, I try to rerun your codes  on cpu,but here are some bugs. In addition to the version of pytorch, are there any other requirements?Thanks

**Comment by newlei** [comment]
At present, the code can only run on GPU, not on CPU.  If you want to run on CPU, you need to modify the GPU-related code.

**Comment by A11en0** [comment]
Hi, I encounter the same problem. Guess due to compatibility with the Pytorch version. Could you please attach the PyTorch version?

**Comment by Littleyezi** [comment]
I have tried different version of Pytorch, like 1.1.0(the author recommand),1.8.0 and the newest version,but all do not work.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "newlei/LR-GCCF"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年6月28日(星期一) 下午3:48
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [newlei/LR-GCCF] About coding cannot directly run (#5)





 
Hi, I encounter the same problem. Guess due to compatibility with the Pytorch version. Could you please attach the PyTorch version?

**Comment by A11en0** [comment]
Finded the problem, just delete `os.environ["CUDA_VISIBLE_DEVICES"] = ','.join(map(str, [1]))` in the line 12 of train_xxx.py. It'll set the GPU only visible on position 1.

**Comment by Littleyezi** [comment]
Thanks for all! But I met a new problem, that shown "BrokenPipeError: [Errno 32] Broken pipe", I run the train_XX.py on windows.Have you met it?&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "newlei/LR-GCCF"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年6月28日(星期一) 下午4:01
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [newlei/LR-GCCF] About coding cannot directly run (#5)





 
Finded the problem, just delete os.environ["CUDA_VISIBLE_DEVICES"] = ','.join(map(str, [1])) in the line 12 of train_xxx.py. It'll set the GPU only visible on position 1.

**Comment by newlei** [comment]
You can retrieve the solution to this problem by yourself. There are many reasons for this error, and the information you give can not determine the specific cause.

I provide solutions for two situations, I hope it will be helpful to you.
1: The question happened because Windows cannot run this DataLoader in 'num_workers' more than 0. 
https://stackoverflow.com/questions/50480689/pytorch-torchvision-brokenpipeerror-errno-32-broken-pipe
2: Not an issue with the code, you can suppress the error.
https://stackoverflow.com/questions/31087483/brokenpipeerror-errno-32-broken-pipe-in-python3
